language: php
sudo: false
php:
  - 5.6
  - 7.0
  - hhvm
  - nightly
env:
  - EXT=none
  - EXT=memcache
  - EXT=memcached
matrix:
  exclude:
    - php: 7.0
      env: EXT=memcache
    - php: nightly
      env: EXT=memcache
services:
  - memcached
before_install:
  - if [[ $EXT = memcache && $TRAVIS_PHP_VERSION != hhvm ]]; then echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ $EXT = memcached && $TRAVIS_PHP_VERSION != hhvm ]]; then echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
install:
  - composer install
script:
  - vendor/bin/phpunit --group standard
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then vendor/bin/phpunit --group $EXT; fi
  - if [[ $TRAVIS_PHP_VERSION = 7.0 || $TRAVIS_PHP_VERSION = nightly ]]; then vendor/bin/phpunit --group 7.0; fi
